# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FontResourcepackGenerator_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(450, 520)
        MainWindow.setMinimumSize(QtCore.QSize(450, 520))
        MainWindow.setMaximumSize(QtCore.QSize(450, 520))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.basic = QtWidgets.QGroupBox(self.centralwidget)
        self.basic.setGeometry(QtCore.QRect(20, 20, 411, 131))
        self.basic.setObjectName("basic")
        self.chosefile_button_1 = QtWidgets.QToolButton(self.basic)
        self.chosefile_button_1.setGeometry(QtCore.QRect(350, 60, 41, 21))
        self.chosefile_button_1.setObjectName("chosefile_button_1")
        self.name = QtWidgets.QLabel(self.basic)
        self.name.setGeometry(QtCore.QRect(20, 30, 31, 20))
        self.name.setObjectName("name")
        self.packpic = QtWidgets.QLabel(self.basic)
        self.packpic.setGeometry(QtCore.QRect(20, 60, 111, 20))
        self.packpic.setObjectName("packpic")
        self.packpic_input = QtWidgets.QLineEdit(self.basic)
        self.packpic_input.setGeometry(QtCore.QRect(140, 60, 201, 22))
        self.packpic_input.setFocusPolicy(QtCore.Qt.NoFocus)
        self.packpic_input.setObjectName("packpic_input")
        self.name_input = QtWidgets.QLineEdit(self.basic)
        self.name_input.setGeometry(QtCore.QRect(60, 30, 331, 22))
        self.name_input.setAcceptDrops(False)
        self.name_input.setInputMask("")
        self.name_input.setObjectName("name_input")
        self.description = QtWidgets.QLabel(self.basic)
        self.description.setGeometry(QtCore.QRect(20, 90, 31, 20))
        self.description.setObjectName("description")
        self.description_input = QtWidgets.QLineEdit(self.basic)
        self.description_input.setGeometry(QtCore.QRect(60, 90, 331, 21))
        self.description_input.setInputMask("")
        self.description_input.setObjectName("description_input")
        self.fontinfo = QtWidgets.QGroupBox(self.centralwidget)
        self.fontinfo.setGeometry(QtCore.QRect(20, 160, 411, 161))
        self.fontinfo.setObjectName("fontinfo")
        self.font = QtWidgets.QLabel(self.fontinfo)
        self.font.setGeometry(QtCore.QRect(20, 30, 31, 20))
        self.font.setObjectName("font")
        self.font_input = QtWidgets.QLineEdit(self.fontinfo)
        self.font_input.setGeometry(QtCore.QRect(60, 30, 281, 22))
        self.font_input.setFocusPolicy(QtCore.Qt.NoFocus)
        self.font_input.setObjectName("font_input")
        self.chosefile_button_2 = QtWidgets.QToolButton(self.fontinfo)
        self.chosefile_button_2.setGeometry(QtCore.QRect(350, 30, 41, 21))
        self.chosefile_button_2.setObjectName("chosefile_button_2")
        self.lateraloffset = QtWidgets.QLabel(self.fontinfo)
        self.lateraloffset.setGeometry(QtCore.QRect(20, 60, 72, 20))
        self.lateraloffset.setObjectName("lateraloffset")
        self.longitudinaloffset = QtWidgets.QLabel(self.fontinfo)
        self.longitudinaloffset.setGeometry(QtCore.QRect(210, 60, 72, 20))
        self.longitudinaloffset.setObjectName("longitudinaloffset")
        self.fontsize = QtWidgets.QLabel(self.fontinfo)
        self.fontsize.setGeometry(QtCore.QRect(20, 90, 71, 20))
        self.fontsize.setObjectName("fontsize")
        self.resolution = QtWidgets.QLabel(self.fontinfo)
        self.resolution.setGeometry(QtCore.QRect(210, 90, 71, 20))
        self.resolution.setObjectName("resolution")
        self.lateraloffset_input = QtWidgets.QLineEdit(self.fontinfo)
        self.lateraloffset_input.setGeometry(QtCore.QRect(100, 60, 101, 22))
        self.lateraloffset_input.setAcceptDrops(False)
        self.lateraloffset_input.setObjectName("lateraloffset_input")
        self.longitudinaloffset_input = QtWidgets.QLineEdit(self.fontinfo)
        self.longitudinaloffset_input.setGeometry(QtCore.QRect(290, 60, 101, 22))
        self.longitudinaloffset_input.setAcceptDrops(False)
        self.longitudinaloffset_input.setObjectName("longitudinaloffset_input")
        self.resolution_input = QtWidgets.QLineEdit(self.fontinfo)
        self.resolution_input.setGeometry(QtCore.QRect(290, 90, 101, 22))
        self.resolution_input.setAcceptDrops(False)
        self.resolution_input.setObjectName("resolution_input")
        self.fontsize_input = QtWidgets.QLineEdit(self.fontinfo)
        self.fontsize_input.setGeometry(QtCore.QRect(100, 90, 101, 22))
        self.fontsize_input.setAcceptDrops(False)
        self.fontsize_input.setObjectName("fontsize_input")
        self.save = QtWidgets.QLabel(self.fontinfo)
        self.save.setGeometry(QtCore.QRect(20, 120, 72, 20))
        self.save.setObjectName("save")
        self.save_input = QtWidgets.QLineEdit(self.fontinfo)
        self.save_input.setGeometry(QtCore.QRect(90, 120, 251, 22))
        self.save_input.setFocusPolicy(QtCore.Qt.NoFocus)
        self.save_input.setAcceptDrops(False)
        self.save_input.setObjectName("save_input")
        self.savefile_button = QtWidgets.QToolButton(self.fontinfo)
        self.savefile_button.setGeometry(QtCore.QRect(350, 120, 41, 21))
        self.savefile_button.setObjectName("savefile_button")
        self.schedule = QtWidgets.QGroupBox(self.centralwidget)
        self.schedule.setGeometry(QtCore.QRect(20, 380, 411, 101))
        self.schedule.setObjectName("schedule")
        self.progressBar = QtWidgets.QProgressBar(self.schedule)
        self.progressBar.setGeometry(QtCore.QRect(20, 60, 381, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.task = QtWidgets.QLabel(self.schedule)
        self.task.setGeometry(QtCore.QRect(20, 30, 72, 20))
        self.task.setObjectName("task")
        self.task_output = QtWidgets.QLineEdit(self.schedule)
        self.task_output.setGeometry(QtCore.QRect(90, 30, 301, 21))
        self.task_output.setFocusPolicy(QtCore.Qt.NoFocus)
        self.task_output.setAcceptDrops(False)
        self.task_output.setObjectName("task_output")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(20, 340, 411, 28))
        self.submit.setObjectName("submit")
        self.author = QtWidgets.QLabel(self.centralwidget)
        self.author.setGeometry(QtCore.QRect(250, 490, 181, 20))
        self.author.setObjectName("author")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Minecraft字体资源包生成器"))
        self.basic.setTitle(_translate("MainWindow", "资源包基础信息"))
        self.chosefile_button_1.setText(_translate("MainWindow", "..."))
        self.name.setText(_translate("MainWindow", "名称"))
        self.packpic.setText(_translate("MainWindow", "封面(pack.png)"))
        self.name_input.setText(_translate("MainWindow", "FontResourcepack"))
        self.description.setText(_translate("MainWindow", "描述"))
        self.description_input.setText(_translate("MainWindow", "Create by FontResourcepack Generator"))
        self.fontinfo.setTitle(_translate("MainWindow", "其他信息"))
        self.font.setText(_translate("MainWindow", "字体"))
        self.font_input.setText(_translate("MainWindow", "C:\\Windows\\Fonts\\simhei.ttf"))
        self.chosefile_button_2.setText(_translate("MainWindow", "..."))
        self.lateraloffset.setText(_translate("MainWindow", "横向偏移量"))
        self.longitudinaloffset.setText(_translate("MainWindow", "纵向偏移量"))
        self.fontsize.setText(_translate("MainWindow", "字母大小"))
        self.resolution.setText(_translate("MainWindow", "解析度"))
        self.lateraloffset_input.setText(_translate("MainWindow", "0"))
        self.longitudinaloffset_input.setText(_translate("MainWindow", "0"))
        self.resolution_input.setText(_translate("MainWindow", "2"))
        self.fontsize_input.setText(_translate("MainWindow", "11"))
        self.save.setText(_translate("MainWindow", "保存位置"))
        self.save_input.setText(_translate("MainWindow", "C:\\Generated packs"))
        self.savefile_button.setText(_translate("MainWindow", "..."))
        self.schedule.setTitle(_translate("MainWindow", "进度"))
        self.task.setText(_translate("MainWindow", "当前任务"))
        self.task_output.setText(_translate("MainWindow", "无"))
        self.submit.setText(_translate("MainWindow", "开始制作"))
        self.author.setText(_translate("MainWindow", "by F-studio SaltedFish"))

